name: CI on Self-Hosted Runner

on:
  push:
    branches: [ main ]  # or any branch you want

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Hello from your self-hosted runner!"
