name: Deploy Flask App to GCP VM
on:
  push:
    branches: [ main ]   # When you push to 'main', this workflow will run

jobs:
  deploy:
    runs-on: ubuntu-latest   # The GitHub Actions machine (not your VM)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Pulls your code from GitHub

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          sudo apt update
          sudo apt install -y python3 python3-venv python3-pip
          if [ ! -d ~/flask-sample-app ]; then
            git clone https://github.com/SuneethaHS1/flask-sample-app.git ~/flask-sample-app
          fi
          cd ~/flask-sample-app
          ./start.sh
        EOF
