name: Deploy Flask App

on:
  push:
    branches: [ main ]  # Trigger when code is pushed to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Make sure your runner has this label

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change if you're using another version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stop existing Gunicorn process (if running)
        run: |
          pkill gunicorn || true  # Will not fail if gunicorn is not running

      - name: Start Flask app with Gunicorn
        run: |
          nohup gunicorn -w 4 -b 0.0.0.0:5000 app:app &
